### ISSUE TITLE
why does not .gitignore file of gaurun contain _vendor?

### ISSUE THREAD

**Issue by catatsuy** [mercari/gaurun#4]
[mattn/gom](https://github.com/mattn/gom) creates the `_vendor` directory by default. But the `.gitignore` file of gaurun contains `.vendor`.

Why does not `.gitignore` file of gaurun contain `_vendor`?

**Comment by cubicdaiya** [comment]
[mattn/gom](https://github.com/mattn/gom) allows changing vendor-path by `GOM_VENDOR_NAME`. 

Usually I use the config below. Because I don't like that external packages are always visible.

```bash
export GOM_VENDOR_NAME=.vendor
```

But it is possible to ignore `.vendor` with `~/.gitignore` instead of `gaurun/.gitignore`. As you mentioned, `gaurun/.gitignore` should contain `_vendor` instead of `.vendor` in general. (Patches welcome!)

**Comment by catatsuy** [comment]
I make the patch #5.
Please merge.
