### ISSUE TITLE
limitation of device token in a params of POST

### ISSUE THREAD

**Issue by takutakahashi** [mercari/gaurun#92]
Hello. This is a question for REST api.
Do you have a size limitation in the param `.notifications.token` when we send a POST request to gaurun?
We want to send 10000+ push notifications with one or frew requests. 
I expect that limitation of size is depends on size limitation of POST request and json format.
I would appreciate if you could answer it.

Thank you.

**Comment by cubicdaiya** [comment]
Gaurun has the size-limitation about `.notifications` instead of `.notifications.token`. This limitation is controllable by [core.notification_max](https://github.com/mercari/gaurun/blob/master/CONFIGURATION.md#core-section) (default value is 100). This value affects only the size of `.notifications`.

So I recommend below

- Always make the size of `.notifications.token` 1
- Instead,  append many **notification** objects to `.notifications`.

**Comment by takutakahashi** [comment]
Thenk you, @cubicdaiya !
Do you have some results of benchmark about size of `.notifications` ?
If not, I can experiment and feedback.

Thank you.

**Comment by cubicdaiya** [comment]
Sorry for late reply. We don't have such as results of benchmark. But it's not severe at all. We usually strore several dozen tokens in `.notifications`.

**Comment by takutakahashi** [comment]
I understand.
We consider to use this amazing product !
Thank you for your answer, @cubicdaiya !
This issue can be closed.
